package com.hermes.agent.skills;

import com.hermes.agent.config.AgentConfig;
import com.hermes.agent.skills.hub.SkillsHubService;
import com.hermes.agent.skills.loader.SkillLoader;
import com.hermes.agent.skills.loader.SkillWriter;
import com.hermes.agent.skills.model.Skill;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * SkillSystem 单元测试
 */
class SkillSystemTest {

    @TempDir
    Path tempDir;

    private SkillSystem skillSystem;
    private SkillLoader loader;
    private SkillWriter writer;
    private SkillsHubService hubService;

    @BeforeEach
    void setUp() {
        AgentConfig config = new AgentConfig();
        try {
            var field = AgentConfig.class.getDeclaredField("skills");
            field.setAccessible(true);
            AgentConfig.SkillsConfig skillsConfig = new AgentConfig.SkillsConfig();
            skillsConfig.setHome(tempDir.toString());
            field.set(config, skillsConfig);
        } catch (Exception e) {
            fail("Failed to set config: " + e.getMessage());
        }
        
        loader = new SkillLoader(config);
        writer = new SkillWriter(loader);
        hubService = mock(SkillsHubService.class);
        
        skillSystem = new SkillSystem(loader, writer, hubService);
    }

    @Test
    void testRegisterAndGetSkill() {
        Skill skill = createSkill("register-test", "Test registration");
        
        skillSystem.registerSkill(skill);
        
        Optional<Skill> retrieved = skillSystem.getSkill("register-test");
        assertTrue(retrieved.isPresent());
        assertEquals("register-test", retrieved.get().getName());
    }

    @Test
    void testGetNonExistentSkill() {
        Optional<Skill> skill = skillSystem.getSkill("non-existent");
        assertFalse(skill.isPresent());
    }

    @Test
    void testSearchSkills() {
        skillSystem.registerSkill(createSkill("git-helper", "Git workflow helper"));
        skillSystem.registerSkill(createSkill("github-pr", "GitHub PR review"));
        skillSystem.registerSkill(createSkill("docker-build", "Docker build helper"));
        
        List<Skill> results = skillSystem.searchSkills("git");
        assertEquals(2, results.size());
        
        results = skillSystem.searchSkills("docker");
        assertEquals(1, results.size());
    }

    @Test
    void testGetAllSkillNames() {
        skillSystem.registerSkill(createSkill("skill1", "First"));
        skillSystem.registerSkill(createSkill("skill2", "Second"));
        skillSystem.registerSkill(createSkill("skill3", "Third"));
        
        List<String> names = skillSystem.getAllSkillNames();
        assertEquals(3, names.size());
        assertTrue(names.contains("skill1"));
        assertTrue(names.contains("skill2"));
        assertTrue(names.contains("skill3"));
    }

    @Test
    void testDeleteSkill() throws IOException {
        Skill skill = createSkill("delete-test", "To be deleted");
        skill.setSource(Skill.Source.CUSTOM);
        skill.setContent("# Test");
        
        skillSystem.registerSkill(skill);
        assertTrue(skillSystem.getSkill("delete-test").isPresent());
        
        boolean deleted = skillSystem.deleteSkill("delete-test");
        assertTrue(deleted);
        assertFalse(skillSystem.getSkill("delete-test").isPresent());
    }

    @Test
    void testDeleteHubSkillFails() throws IOException {
        Skill skill = createSkill("hub-skill", "From Hub");
        skill.setSource(Skill.Source.HUB);
        skill.setContent("# Hub Skill");
        
        skillSystem.registerSkill(skill);
        
        boolean deleted = skillSystem.deleteSkill("hub-skill");
        assertFalse(deleted); // Hub 技能不能直接删除
        assertTrue(skillSystem.getSkill("hub-skill").isPresent());
    }

    @Test
    void testAutoGeneratedFlag() {
        Skill skill = createSkill("auto-skill", "Auto generated");
        skillSystem.registerSkill(skill);
        skillSystem.markAutoGenerated("auto-skill");
        
        assertTrue(skillSystem.isAutoGenerated("auto-skill"));
        Set<String> autoSkills = skillSystem.getAutoGeneratedSkillNames();
        assertTrue(autoSkills.contains("auto-skill"));
    }

    @Test
    void testBuildSkillsPrompt() {
        Skill skill1 = createSkill("prompt-skill-1", "First skill");
        skill1.setContent("# First\n\nContent 1");
        
        Skill skill2 = createSkill("prompt-skill-2", "Second skill");
        skill2.setContent("# Second\n\nContent 2");
        
        skillSystem.registerSkill(skill1);
        skillSystem.registerSkill(skill2);
        
        String prompt = skillSystem.buildSkillsPrompt(Set.of("prompt-skill-1", "prompt-skill-2"));
        
        assertTrue(prompt.contains("prompt-skill-1"));
        assertTrue(prompt.contains("prompt-skill-2"));
        assertTrue(prompt.contains("# First"));
        assertTrue(prompt.contains("# Second"));
    }

    @Test
    void testGetSkillStats() {
        skillSystem.registerSkill(createSkill("stats-1", "First"));
        skillSystem.registerSkill(createSkill("stats-2", "Second"));
        skillSystem.markAutoGenerated("stats-2");
        
        Map<String, Object> stats = skillSystem.getSkillStats();
        
        assertEquals(2, stats.get("total_skills"));
        assertEquals(1, stats.get("auto_generated"));
        assertNotNull(stats.get("skill_names"));
    }

    @Test
    void testReload() throws IOException {
        // 创建技能文件
        createSkillFile(tempDir, "custom", "reload-test", "Reload Test", "Testing reload");
        
        // 初始加载
        skillSystem.loadSkills();
        assertTrue(skillSystem.getSkill("reload-test").isPresent());
        
        // 修改文件
        Path skillFile = tempDir.resolve("custom").resolve("reload-test").resolve("SKILL.md");
        String newContent = Files.readString(skillFile).replace("Testing reload", "Updated description");
        Files.writeString(skillFile, newContent);
        
        // 重载
        skillSystem.reload();
        
        // 验证更新（由于重载会重新读取文件）
        Optional<Skill> updated = skillSystem.getSkill("reload-test");
        assertTrue(updated.isPresent());
    }

    // 辅助方法
    private Skill createSkill(String name, String description) {
        Skill skill = new Skill();
        skill.setName(name);
        skill.setDescription(description);
        skill.setVersion("1.0.0");
        skill.setAuthor("Test");
        skill.setSource(Skill.Source.CUSTOM);
        skill.setPlatforms(Arrays.asList("linux", "macos", "windows"));
        return skill;
    }

    private void createSkillFile(Path root, String source, String name, String displayName, String desc) throws IOException {
        String content = String.format("""
            ---
            name: %s
            description: %s
            version: 1.0.0
            ---
            
            # %s
            """, name, desc, displayName);
        
        Path skillDir = root.resolve(source).resolve(name);
        Files.createDirectories(skillDir);
        Files.writeString(skillDir.resolve("SKILL.md"), content);
    }
}
