import { sessionStore } from './sessionStore'

function currentSid() { return sessionStore.currentSessionId || 'default' }

const BASE = 'http://localhost:8993/api' // 匹配 ChatController 的 /api 前缀

async function request<T>(path: string, opts?: RequestInit): Promise<T> {
  const res = await fetch(BASE + path, {
    headers: { 'Content-Type': 'application/json' },
    ...opts,
  })
  if (!res.ok) {
    // Try to read error body from server (JSON with error/message field)
    let detail = ''
    try {
      const text = await res.text()
      if (text) {
        try {
          const json = JSON.parse(text)
          detail = json.error || json.message || json.detail || text
        } catch {
          detail = text.substring(0, 200)
        }
      }
    } catch { /* ignore */ }
    throw new Error(`${res.status} ${res.statusText}${detail ? ': ' + detail : ''}`)
  }
  return res.json() as Promise<T>
}

// ── Chat ──────────────────────────────────────────────────────────────

// 第一个参数是 message，sessionId 可选（自动使用当前选中会话）
// 后端端点：POST /api/chat（ChatController）
// 请求体：{ sessionId: "...", message: "..." }
export async function sendChat(message: string, sessionId?: string) {
  const sid = sessionId ?? currentSid()
  sessionStore.currentSessionId = sid
  return request<{ response: string; error?: string; sessionId: string }>('/chat', {
    method: 'POST',
    body: JSON.stringify({ sessionId: sid, message }),
  })
}

// 第一个参数是 message，sessionId 可选
// 后端端点：POST /api/chat/stream（ChatController）
export async function* streamChat(message: string, sessionId?: string) {
  const sid = sessionId ?? currentSid()
  sessionStore.currentSessionId = sid
  const res = await fetch(`${BASE}/chat/stream?sessionId=${encodeURIComponent(sid)}&message=${encodeURIComponent(message)}`, {
    method: 'POST',
  })
  if (!res.ok) throw new Error(`${res.status}`)
  const reader = res.body!.getReader()
  const decoder = new TextDecoder()
  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    yield decoder.decode(value)
  }
}

// ── Sessions ─────────────────────────────────────────────────────────

export async function getSessions() {
  return request<{ activeSessions: string[]; count: number }>('/sessions')
}

export async function clearSession(sessionId: string) {
  return request<{ cleared: string }>(`/sessions/${encodeURIComponent(sessionId)}`, { method: 'DELETE' })
}

export async function getSessionMessages(sessionId: string, limit = 100) {
  return request<{ sessionId: string; messages: { role: string; content: string; timestamp: number }[]; count: number }>(
    `/messages?sessionId=${encodeURIComponent(sessionId)}&limit=${limit}`
  )
}

// ── Scheduler ────────────────────────────────────────────────────────

export async function getJobs() {
  return request<any[]>('/scheduler/jobs')
}

export async function scheduleJob(cron: string, task: string, sessionId = 'default') {
  return request<{ jobId: string; scheduled: boolean }>('/scheduler/jobs', {
    method: 'POST',
    body: JSON.stringify({ cron, task, sessionId }),
  })
}

export async function cancelJob(jobId: string) {
  return request<{ cancelled: string }>(`/scheduler/jobs/${encodeURIComponent(jobId)}`, { method: 'DELETE' })
}

// ── Sub-Agents ──────────────────────────────────────────────────────

export async function getSubAgents() {
  return request<any[]>('/subagents')
}

export async function spawnSubAgent(task: string, sessionId = 'default') {
  return request<{ result: string; task: string }>('/subagents', {
    method: 'POST',
    body: JSON.stringify({ task, sessionId }),
  })
}

export async function killSubAgent(subAgentId: string) {
  return request<{ killed: string }>(`/subagents/${encodeURIComponent(subAgentId)}`, { method: 'DELETE' })
}

// ══════════════════════════════════════════════════════
//  三类记忆自动维护 — API
// ══════════════════════════════════════════════════════

// ── 1. 技能列表 ────────────────────────────────────────────────────

export interface Skill {
  name: string
  description: string
  version?: string
  author?: string
  license?: string
  platforms?: string[]
  prerequisites?: {
    commands?: string[]
    envVars?: string[]
    files?: string[]
  }
  content?: string        // Markdown 正文
  metadata?: Record<string, any>
  source?: 'hub' | 'custom' | 'auto-generated'
  createdAt?: string
  updatedAt?: string
  filePath?: string
  // Legacy compatibility
  autoGenerated?: boolean // deprecated: use source instead
  tags?: string[]         // from metadata.hermes.tags
  category?: string       // legacy: category name
  parameters?: Array<{name: string; type: string; description: string}> // legacy
  steps?: string[]        // legacy: execution steps
  triggers?: string[]     // legacy: trigger patterns
  useCount?: number       // legacy: usage count
  successRate?: string    // legacy: success rate
  lastUsed?: number       // legacy: last usage timestamp
}

export async function getSkills(search?: string) {
  const qs = search ? `?search=${encodeURIComponent(search)}` : ''
  return request<{ skills: Skill[]; count: number; search?: string }>(`/skills${qs}`)
}

export async function deleteSkill(name: string) {
  return request<{ note: string; name: string }>(`/skills/${encodeURIComponent(name)}`, { method: 'DELETE' })
}

export async function getSkillDetail(name: string) {
  return request<Skill>(`/skills/${encodeURIComponent(name)}`)
}

export async function searchSkills(query: string) {
  return request<{ skills: Skill[]; count: number }>(`/skills/search?q=${encodeURIComponent(query)}`)
}

export async function reloadSkills() {
  return request<{ reloaded: number }>('skills/reload', { method: 'POST' })
}

// ── Skills Hub API ────────────────────────────────────────────────────

export interface HubSkill {
  id: string
  name: string
  description: string
  version: string
  author: string
  tags: string[]
  platforms: string[]
}

export interface UpdateInfo {
  name: string
  currentVersion: string
  latestVersion: string
  hasUpdate: boolean
}

export async function hubSearch(q: string) {
  return request<HubSkill[]>(`/skills/hub/search?q=${encodeURIComponent(q)}`)
}

export async function hubInspect(skillId: string) {
  return request<string>(`/skills/hub/inspect/${encodeURIComponent(skillId)}`)
}

export async function hubInstall(skillId: string) {
  return request<Skill>(`/skills/hub/install/${encodeURIComponent(skillId)}`, { method: 'POST' })
}

export async function hubInstallMultiple(skillIds: string[]) {
  return request<Skill[]>('/skills/hub/install', {
    method: 'POST',
    body: JSON.stringify(skillIds),
  })
}

export async function hubCheckUpdates() {
  return request<UpdateInfo[]>('/skills/hub/updates')
}

export async function hubUpdateAll() {
  return request<Skill[]>('/skills/hub/update-all', { method: 'POST' })
}

export async function hubAddTap(repoUrl: string) {
  return request<void>('/skills/hub/tap', {
    method: 'POST',
    body: JSON.stringify({ repo_url: repoUrl }),
  })
}

export async function hubGetTaps() {
  return request<string[]>('/skills/hub/taps')
}

// ── 2. 会话摘要 ───────────────────────────────────────────────────

export interface SummaryStatus {
  sessionId: string
  summaryCount: number
  lastSummary: string
  messageCount: number
  threshold: number
  needsSummary: boolean
}

export async function getSummaryStatus(sessionId: string) {
  return request<SummaryStatus>(`/memory/summary/${encodeURIComponent(sessionId)}`)
}

export async function getAllSummaryStatuses() {
  return request<{ sessions: SummaryStatus[]; total: number }>('/memory/summaries')
}

// ── 3. 用户画像 ───────────────────────────────────────────────────

export interface UserProfile {
  userId: string
  known: boolean
  conversationCount: number
  preferences: Record<string, any>
  topics: string[]
  summary: string
  lastUpdated: string
}

export async function getProfile(sessionId: string) {
  return request<UserProfile>(`/memory/profile/${encodeURIComponent(sessionId)}`)
}

export async function getAllProfiles() {
  return request<{ profiles: UserProfile[]; total: number }>('/memory/profiles')
}

// ── 4. 技能生成 ──────────────────────────────────────────────────

export async function triggerSkillGeneration() {
  return request<{
    triggered: boolean
    totalAutoSkills: number
    autoSkills: Skill[]
    message: string
  }>('/memory/skills/generate', { method: 'POST' })
}

// ── 5. 记忆总览 ───────────────────────────────────────────────────

export interface MemoryStats {
  activeSessions: number
  totalSummaries: number
  totalSkills: number
  autoSkills: number
  registeredSkills: string[]
  dataDir: string
  persistenceEnabled: boolean
  memoryProviders: Array<{ name: string; available: boolean }>
  searchIndex: { totalDocuments: number; uniqueTokens: number; indexedSessions: number }
  memoryTypes: Array<{ type: string; enabled: boolean; description: string }>
}

export async function getMemoryStats() {
  return request<MemoryStats>('/memory/stats')
}

// ══════════════════════════════════════════════════════
//  持久化记忆 API（MEMORY.md / USER.md）
// ══════════════════════════════════════════════════════

export interface CuratedMemoryEntry {
  success: boolean
  target: string
  entries: string[]
  usage: string
  entry_count: number
  message?: string
  error?: string
}

export async function getCuratedMemory(target: 'memory' | 'user') {
  return request<CuratedMemoryEntry>(`/memory/curated/${target}`)
}

export async function curatedMemoryAction(action: 'add' | 'replace' | 'remove' | 'read',
                                           target: 'memory' | 'user',
                                           opts?: { content?: string; old_text?: string }) {
  const body: Record<string, string> = { action, target }
  if (opts?.content) body.content = opts.content
  if (opts?.old_text) body.old_text = opts.old_text
  return request<CuratedMemoryEntry>('/memory/curated', {
    method: 'POST',
    body: JSON.stringify(body),
  })
}

// ══════════════════════════════════════════════════════
//  会话搜索 API
// ══════════════════════════════════════════════════════

export interface SearchResult {
  sessionId: string
  role: string
  content: string
  relevanceScore: string
  hitCount: number
}

export async function searchHistory(query: string, sessionId?: string, limit = 10) {
  const qs = new URLSearchParams({ query, limit: String(limit) })
  if (sessionId) qs.set('sessionId', sessionId)
  return request<{ query: string; results: SearchResult[]; count: number }>(`/memory/search?${qs}`)
}

export async function getSearchStats() {
  return request<{ totalDocuments: number; uniqueTokens: number; indexedSessions: number }>('/memory/search/stats')
}

// ====================  Backward compatibility aliases  ====================
export const chat = sendChat
export const deleteSession = clearSession
export const createJob = scheduleJob
export const deleteJob = cancelJob

// ══════════════════════════════════════════════════════
//  RL Training API
// ══════════════════════════════════════════════════════

export interface RLEnvironment {
  name: string
  class_name: string
  file_path: string
  description: string
  config_class: string
}

export interface RLConfigField {
  name: string
  type: string
  default: any
  description: string
  locked: boolean
  current_value: any
}

export interface RLRunState {
  run_id: string
  environment: string
  status: string
  running_time_minutes: number
  wandb_project: string
  wandb_run_name: string
  error?: string
}

export interface RLRequirements {
  ready: boolean
  python_311_plus: boolean
  has_tinker_key: boolean
  has_wandb_key: boolean
  has_tinker_submodule: boolean
  missing_requirements: string[]
}

export async function rlListEnvironments() {
  return request<{ environments: RLEnvironment[]; count: number }>('/rl/environments')
}

export async function rlSelectEnvironment(name: string) {
  return request<any>('/rl/environments/select', {
    method: 'POST',
    body: JSON.stringify({ name }),
  })
}

export async function rlGetConfig() {
  return request<any>('/rl/config')
}

export async function rlEditConfig(field: string, value: any) {
  return request<any>('/rl/config/edit', {
    method: 'POST',
    body: JSON.stringify({ field, value }),
  })
}

export async function rlStartTraining() {
  return request<any>('/rl/training/start', { method: 'POST' })
}

export async function rlCheckStatus(runId: string) {
  return request<any>(`/rl/training/status/${encodeURIComponent(runId)}`)
}

export async function rlStopTraining(runId: string) {
  return request<any>(`/rl/training/stop/${encodeURIComponent(runId)}`, { method: 'POST' })
}

export async function rlGetResults(runId: string) {
  return request<any>(`/rl/training/results/${encodeURIComponent(runId)}`)
}

export async function rlListRuns() {
  return request<{ runs: RLRunState[]; count: number }>('/rl/training/runs')
}

export async function rlGetRequirements() {
  return request<RLRequirements>('/rl/requirements')
}

export async function rlCompressTrajectories(inputDir: string, outputDir?: string, maxTokens = 16384, samplePercent = 0) {
  return request<any>('/rl/trajectory/compress', {
    method: 'POST',
    body: JSON.stringify({ input_dir: inputDir, output_dir: outputDir || '', max_tokens: maxTokens, sample_percent: samplePercent }),
  })
}

// ══════════════════════════════════════════════════════════════
//  Honcho API (/honcho/*) — 用户画像增强
// ══════════════════════════════════════════════════════════════

// Honcho 系统状态
export interface HonchoStatus {
  active: boolean
  recall_mode: string
  observation_mode: string
  dialectic_depth: number
  dialectic_cadence: number
  dialectic_reasoning_level: string
  extraction_enabled: boolean
  tools_count: number
  tools_available: boolean
  session_strategy: string
  semantic_search: boolean
  embedding_backend: string
}

export async function getHonchoStatus() {
  return request<HonchoStatus>('/honcho/status')
}

// 用户画像 Profile
export interface HonchoProfile {
  peer_id: string
  peer_type: string
  observation_mode: string
  card: Record<string, any>
  card_version: number
  representation: string
  observation_count: number
  conclusion_count: number
  created_at: number
  last_updated: number
}

export async function getHonchoProfile(sessionId: string) {
  return request<HonchoProfile>(`/honcho/profile/${encodeURIComponent(sessionId)}`)
}

// 画像上下文
export async function getHonchoContext(sessionId: string, maxChars = 2000) {
  const qs = new URLSearchParams({ limit: String(maxChars) })
  return request<{ context: string; length: number }>(`/honcho/profile/${encodeURIComponent(sessionId)}/context?${qs}`)
}

// Conclusions 列表
export interface HonchoConclusion {
  id: string
  fact: string
  source: string
  timestamp: number
}

export async function getHonchoConclusions(sessionId: string) {
  return request<{ conclusions: HonchoConclusion[]; total: number }>(`/honcho/profile/${encodeURIComponent(sessionId)}/conclusions`)
}

// 添加结论
export async function addHonchoConclusion(sessionId: string, fact: string) {
  return request<{ success: boolean; id: string; fact: string }>(`/honcho/profile/${encodeURIComponent(sessionId)}/conclude`, {
    method: 'POST',
    body: JSON.stringify({ fact }),
  })
}

// 删除结论
export async function deleteHonchoConclusion(sessionId: string, conclusionId: string) {
  return request<{ success: boolean; deleted_id: string }>(
    `/honcho/profile/${encodeURIComponent(sessionId)}/conclusions/${encodeURIComponent(conclusionId)}`,
    { method: 'DELETE' }
  )
}

// 初始化会话画像
export async function initHonchoSession(sessionId: string, title?: string, peerName?: string) {
  return request<{ success: boolean; session: string; user_peer: string }>(
    `/honcho/session/${encodeURIComponent(sessionId)}/init`,
    {
      method: 'POST',
      body: JSON.stringify({ title: title || sessionId, peerName }),
    }
  )
}

// Seed 身份
export async function seedHonchoIdentity(sessionId: string, type: 'user' | 'ai', content: string) {
  return request<{ success: boolean; type: string; content_length: number }>(
    `/honcho/profile/${encodeURIComponent(sessionId)}/seed`,
    {
      method: 'POST',
      body: JSON.stringify({ type, content }),
    }
  )
}

// 触发画像提取
export async function extractHonchoProfile(sessionId: string, deep = false) {
  return request<{ success: boolean; session: string; deep: boolean }>(
    `/honcho/profile/${encodeURIComponent(sessionId)}/extract?deep=${deep}`,
    { method: 'POST' }
  )
}

// Honcho Liveness
export interface HonchoLiveness {
  session_id: string
  observation_count: number
  conclusion_count: number
  last_observation: number
  last_conclusion: number
  dialectic_active: boolean
  context_chars: number
}

export async function getHonchoLiveness(sessionId: string) {
  return request<HonchoLiveness>(`/honcho/liveness/${encodeURIComponent(sessionId)}`)
}

// Honcho 向量统计
export interface HonchoVectorStats {
  session_id: string
  index_size: number
  last_indexed: number
}

export async function getHonchoVectorStats(sessionId: string) {
  return request<HonchoVectorStats>(`/honcho/vectors/${encodeURIComponent(sessionId)}`)
}

// 语义搜索
export async function honchoSearch(query: string, sessionId = 'default', peer = 'user', maxTokens = 800) {
  return request<{ success: boolean; query: string; result: string }>('/honcho/search', {
    method: 'POST',
    body: JSON.stringify({ query, sessionId, peer, max_tokens: maxTokens }),
  })
}

// ══════════════════════════════════════════════════════════════
//  AgentLoop API (/agent/*) — 多轮工具调用
// ══════════════════════════════════════════════════════════════

// AgentLoop 简单对话（返回最终响应）
export async function agentChat(message: string, sessionId?: string) {
  const sid = sessionId ?? currentSid()
  return request<{ response: string; sessionId: string }>('/agent/chat', {
    method: 'POST',
    body: JSON.stringify({ message, sessionId: sid }),
  })
}

// AgentLoop 流式对话
export async function* agentChatStream(message: string, sessionId?: string) {
  const sid = sessionId ?? currentSid()
  const res = await fetch(`${BASE}/agent/chat/stream?sessionId=${encodeURIComponent(sid)}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message }),
  })
  if (!res.ok) throw new Error(`${res.status}`)
  const reader = res.body!.getReader()
  const decoder = new TextDecoder()
  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    yield decoder.decode(value)
  }
}

// AgentLoop 高级运行（返回完整元数据）
export interface AgentRunResult {
  finalResponse: string
  iterations: number
  completed: boolean
  interrupted: boolean
  exitReason: string
  sessionId: string
  messageCount: number
}

export async function agentRun(message: string, sessionId?: string, maxIterations = 90) {
  const sid = sessionId ?? currentSid()
  return request<AgentRunResult>('/agent/run', {
    method: 'POST',
    body: JSON.stringify({
      messages: [{ role: 'user', content: message }],
      sessionId: sid,
      maxIterations,
    }),
  })
}

// AgentLoop 中断
export async function agentInterrupt(sessionId: string) {
  return request<{ status: string; sessionId: string }>(`/agent/loop/${encodeURIComponent(sessionId)}/interrupt`, {
    method: 'POST',
  })
}

// AgentLoop 引导
export async function agentSteer(sessionId: string, guidance: string) {
  return request<{ status: string; sessionId: string }>(`/agent/loop/${encodeURIComponent(sessionId)}/steer`, {
    method: 'POST',
    body: JSON.stringify({ guidance }),
  })
}

// AgentLoop 活跃列表
export async function getAgentLoops() {
  return request<{ activeLoops: string[]; count: number }>('/agent/loops')
}

// AgentLoop 健康检查
export interface AgentHealth {
  status: string
  maxIterations: number
}

export async function getAgentHealth() {
  return request<AgentHealth>('/agent/health')
}
