package com.hermes.agent.autonomous;

import com.hermes.agent.llm.LLMService;
import com.hermes.agent.model.Message;
import com.hermes.agent.skills.SkillSystem;
import com.hermes.agent.skills.model.Skill;
import com.hermes.agent.skills.model.Skill.Prerequisites;
import com.hermes.agent.skills.model.Skill.Source;
import com.hermes.agent.skills.loader.SkillWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * 技能提炼器 — 自动学习闭环
 * 
 * 职责：
 *   1. 监听子 Agent 的成功任务，自动提炼为可复用技能
 *   2. 从重复出现的问题模式中生成预防性技能
 *   3. 生成标准 SKILL.md 格式并持久化
 *
 * 工作流程：
 *   SubAgentService.spawnSubAgent() 成功后 → 触发 onTaskSuccess()
 *   AutonomousLearner 定时扫描 → 触发 detectAndGenerateSkills()
 */
@Component
public class SkillGenerator {

    private static final Logger log = LoggerFactory.getLogger(SkillGenerator.class);

    private final LLMService llmService;
    private final SkillSystem skillSystem;
    private final SkillWriter skillWriter;

    /** 已生成的技能模板（防止重复生成）key: 任务类型指纹 */
    private final Map<String, GeneratedSkill> generatedSkills = new ConcurrentHashMap<>();

    /** 子 Agent 任务记录（用于分析成功模式） */
    private final List<TaskRecord> taskHistory = Collections.synchronizedList(new ArrayList<>());

    /** 成功关键词（用于判断子 Agent 任务是否成功） */
    private static final Set<String> SUCCESS_INDICATORS = Set.of(
            "completed", "done", "finished", "succeeded", "success",
            "完成", "成功", "搞定", "已解决"
    );

    /** 最小任务重复次数才触发生成 */
    private static final int MIN_TASK_REPEATS = 2;

    /** 高频技术主题 */
    private static final Set<String> TECH_TOPICS = Set.of(
            "java", "spring", "python", "javascript", "typescript", "vue", "react",
            "docker", "kubernetes", "mysql", "redis", "mongodb", "git", "linux",
            "api", "rest", "microservice", "cache", "security", "性能", "架构",
            "部署", "测试", "llm", "ai", "sql", "oauth", "jwt", "websocket"
    );

    public SkillGenerator(LLMService llmService, SkillSystem skillSystem, SkillWriter skillWriter) {
        this.llmService = llmService;
        this.skillSystem = skillSystem;
        this.skillWriter = skillWriter;
    }

    /**
     * 子 Agent 任务完成时由 SubAgentService 调用
     *
     * @param task       原始任务描述
     * @param result     任务执行结果
     * @param sessionId 所属会话
     */
    @Async
    public void onTaskSuccess(String task, String result, String sessionId) {
        if (task == null || task.isBlank()) return;

        // 记录任务历史
        taskHistory.add(new TaskRecord(task, result, sessionId, Instant.now()));
        log.info("[SkillGen] 检测到成功任务: {}", truncate(task, 80));

        // 检查是否可以生成技能
        if (canGenerate(task)) {
            generateSkillFromTask(task, result, sessionId);
        }
    }

    /**
     * 定时扫描对话历史，检测高频主题并生成技能
     */
    @Scheduled(fixedRate = 3600000)  // 每小时
    public void detectAndGenerateSkills() {
        if (taskHistory.size() < 5) return;

        log.info("[SkillGen] 开始扫描高频主题...");

        // 分析高频技术主题
        Map<String, Integer> topicFrequency = analyzeTopicFrequency();

        int generated = 0;
        for (Map.Entry<String, Integer> entry : topicFrequency.entrySet()) {
            if (entry.getValue() < 3) continue;  // 至少出现 3 次

            String topic = entry.getKey();
            String fingerprint = fingerprint(topic);

            // 跳过已生成的
            if (generatedSkills.containsKey(fingerprint)) continue;
            if (skillSystem.getSkill(topicToSkillName(topic)).isPresent()) continue;

            log.info("[SkillGen] 主题 '{}' 出现 {} 次，触发技能生成", topic, entry.getValue());
            
            try {
                generateSkillFromTopic(topic);
                generated++;
            } catch (Exception e) {
                log.warn("[SkillGen] 主题技能生成失败: {}", e.getMessage());
            }
        }

        if (generated > 0) {
            log.info("[SkillGen] 本次生成 {} 个主题技能", generated);
        }
    }

    /**
     * 获取所有自动生成的技能
     */
    public List<GeneratedSkill> getGeneratedSkills() {
        return new ArrayList<>(generatedSkills.values());
    }

    /**
     * 获取技能使用建议（按频率排序）
     */
    public List<String> getSuggestedSkills() {
        return generatedSkills.values().stream()
                .sorted(Comparator.comparingInt(GeneratedSkill::getUseCount).reversed())
                .limit(5)
                .map(GeneratedSkill::getName)
                .collect(Collectors.toList());
    }

    public int getAutoGeneratedCount() {
        return generatedSkills.size();
    }

    // === 私有方法 ===

    private boolean canGenerate(String task) {
        String fp = fingerprint(task);
        
        // 至少有 MIN_TASK_REPEATS 个相似任务
        long similarCount = taskHistory.stream()
                .filter(r -> fingerprint(r.task).equals(fp))
                .count();
        
        return similarCount >= MIN_TASK_REPEATS && !generatedSkills.containsKey(fp);
    }

    private void generateSkillFromTask(String task, String result, String sessionId) {
        String skillName = buildSkillName(task);
        String fingerprint = fingerprint(task);

        // 检查是否已存在
        if (skillSystem.getSkill(skillName).isPresent()) {
            log.debug("[SkillGen] 技能 '{}' 已存在，跳过", skillName);
            return;
        }

        try {
            // 调用 LLM 生成 SKILL.md 内容
            String skillContent = invokeSkillGeneration(task, result);

            // 创建 Skill 对象
            Skill skill = new Skill();
            skill.setName(skillName);
            skill.setDescription("自动生成的技能: " + truncate(task, 100));
            skill.setVersion("1.0.0");
            skill.setAuthor("SkillGenerator");
            skill.setSource(Source.AUTO_GENERATED);
            skill.setContent(skillContent);
            skill.setPlatforms(Arrays.asList("linux", "macos", "windows"));

            // 设置元数据
            Map<String, Object> metadata = new LinkedHashMap<>();
            metadata.put("tags", extractTags(task));
            
            Map<String, Object> hermesMeta = new LinkedHashMap<>();
            hermesMeta.put("auto_generated", true);
            hermesMeta.put("trigger_task", truncate(task, 200));
            hermesMeta.put("generated_at", Instant.now().toString());
            metadata.put("hermes", hermesMeta);
            
            skill.setMetadata(metadata);

            // 保存到文件系统
            skillWriter.save(skill);

            // 注册到内存
            skillSystem.registerSkill(skill);
            skillSystem.markAutoGenerated(skillName);

            // 记录已生成
            generatedSkills.put(fingerprint, new GeneratedSkill(
                skillName, task, skillContent, Instant.now(), 0
            ));

            log.info("[SkillGen] ✓ 技能 '{}' 生成成功，已保存到 auto-generated/{}/SKILL.md",
                skillName, skillName);

        } catch (Exception e) {
            log.error("[SkillGen] 生成失败 task={}: {}", truncate(task, 50), e.getMessage());
        }
    }

    private void generateSkillFromTopic(String topic) {
        String skillName = buildSkillName(topic);

        if (skillSystem.getSkill(skillName).isPresent()) return;

        try {
            // 构建主题相关的上下文
            String context = buildTopicContext(topic);
            String skillContent = invokeTopicSkillGeneration(topic, context);

            // 创建 Skill 对象
            Skill skill = new Skill();
            skill.setName(skillName);
            skill.setDescription("自动生成的技能（主题: " + topic + "）");
            skill.setVersion("1.0.0");
            skill.setAuthor("SkillGenerator");
            skill.setSource(Source.AUTO_GENERATED);
            skill.setContent(skillContent);
            skill.setPlatforms(Arrays.asList("linux", "macos", "windows"));

            // 设置元数据
            Map<String, Object> metadata = new LinkedHashMap<>();
            metadata.put("tags", Arrays.asList(topic, "auto-generated"));
            
            Map<String, Object> hermesMeta = new LinkedHashMap<>();
            hermesMeta.put("auto_generated", true);
            hermesMeta.put("topic", topic);
            hermesMeta.put("generated_at", Instant.now().toString());
            metadata.put("hermes", hermesMeta);
            
            skill.setMetadata(metadata);

            // 保存并注册
            skillWriter.save(skill);
            skillSystem.registerSkill(skill);
            skillSystem.markAutoGenerated(skillName);

            generatedSkills.put(fingerprint(topic), new GeneratedSkill(
                skillName, topic, skillContent, Instant.now(), 0
            ));

            log.info("[SkillGen] ✓ 主题技能 '{}' 生成成功", skillName);

        } catch (Exception e) {
            log.error("[SkillGen] 主题技能生成失败 topic={}: {}", topic, e.getMessage());
        }
    }

    /**
     * 调用 LLM 生成 SKILL.md 内容
     */
    private String invokeSkillGeneration(String task, String result) {
        String prompt = """
            你是一个技能工程师。请根据以下成功案例，生成一个标准格式的 SKILL.md 文档。

            任务描述：%s
            执行结果摘要：%s

            请生成符合以下格式的技能文档（Markdown正文，不含YAML frontmatter）：

            # 技能标题

            ## 适用场景
            描述什么情况下使用此技能

            ## 执行步骤
            1. 第一步
            2. 第二步

            ## 示例命令
            ```bash
            # 实际命令示例
            ```

            ## 注意事项
            - 常见问题
            - 最佳实践

            只输出 Markdown 正文内容，不要有前言或结语。
            """.formatted(task, truncate(result, 500));

        try {
            Message response = llmService.chat(
                List.of(
                    new Message("system", "你是专业的技能工程师，输出结构清晰、可直接使用的技能文档。", Instant.now()),
                    new Message("user", prompt, Instant.now())
                ),
                "skill-gen-" + UUID.randomUUID().toString().substring(0, 8)
            ).block();

            return response != null && response.getContent() != null
                ? response.getContent().trim()
                : "# 自动生成技能\n\n内容生成失败，请手动编辑。";
        } catch (Exception e) {
            log.warn("[SkillGen] LLM调用失败: {}", e.getMessage());
            return "# " + truncate(task, 50) + "\n\n## 适用场景\n遇到类似任务时使用。\n\n## 执行步骤\n请手动补充。";
        }
    }

    private String invokeTopicSkillGeneration(String topic, String context) {
        return """
            # %s 技能

            ## 适用场景
            处理与 "%s" 相关的问题和任务时使用此技能。

            ## 执行步骤
            1. 理解问题的具体需求
            2. 分析相关上下文
            3. 制定解决方案
            4. 执行并验证

            ## 已知上下文
            %s

            ## 注意事项
            - 结合实际情况灵活调整
            - 优先参考历史成功经验
            - 注意版本兼容性问题
            """.formatted(topic, topic, truncate(context, 300));
    }

    private String fingerprint(String task) {
        // 归一化：取关键词小写，去除空格和标点
        String normalized = task.toLowerCase()
                .replaceAll("[^a-z0-9\\u4e00-\\u9fa5]", "")
                .trim();
        // 截取前 40 字符作为指纹
        return normalized.length() > 40 ? normalized.substring(0, 40) : normalized;
    }

    private String buildSkillName(String task) {
        String[] words = task.split("[\\s\\-_/,.，。、+/]+");
        StringBuilder name = new StringBuilder();
        int count = 0;
        
        for (String w : words) {
            if (w.length() < 2) continue;
            
            if (containsChinese(w)) {
                name.append(w);
                count++;
                if (count >= 2) break;
            } else {
                name.append(w.toLowerCase());
                count++;
                if (count >= 3) break;
            }
            
            if (count < words.length && count > 0) name.append("_");
        }
        
        String result = name.toString().replaceAll("[^a-z0-9_\\u4e00-\\u9fa5]", "");
        if (result.length() > 30) result = result.substring(0, 30);
        
        return (result.isEmpty() ? "skill_" + System.currentTimeMillis() : result) + "_auto";
    }

    private String topicToSkillName(String topic) {
        return topic.toLowerCase().replaceAll("[^a-z0-9]", "_") + "_auto";
    }

    private List<String> extractTags(String task) {
        List<String> tags = new ArrayList<>();
        String lower = task.toLowerCase();
        
        for (String kw : TECH_TOPICS) {
            if (lower.contains(kw)) {
                tags.add(kw);
            }
        }
        
        if (tags.isEmpty()) {
            tags.add("auto-generated");
        }
        
        return tags;
    }

    private Map<String, Integer> analyzeTopicFrequency() {
        Map<String, Integer> frequency = new HashMap<>();

        for (TaskRecord record : taskHistory) {
            String content = record.task.toLowerCase();
            for (String topic : TECH_TOPICS) {
                if (content.contains(topic)) {
                    frequency.merge(topic, 1, Integer::sum);
                }
            }
        }

        return frequency.entrySet().stream()
                .filter(e -> e.getValue() >= 3)
                .sorted(Map.Entry.<String, Integer>comparingByValue().reversed())
                .limit(10)
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
    }

    private String buildTopicContext(String topic) {
        StringBuilder sb = new StringBuilder();
        
        for (TaskRecord record : taskHistory) {
            if (record.task != null && record.task.toLowerCase().contains(topic)) {
                sb.append("【").append(truncate(record.task, 50)).append("】\n");
            }
        }
        
        return sb.length() > 0 ? sb.toString() : "（无相关历史上下文）";
    }

    private boolean containsChinese(String s) {
        return s.codePoints().anyMatch(cp -> cp >= 0x4E00 && cp <= 0x9FA5);
    }

    private String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max) + "...";
    }

    // === 内部数据类 ===

    public static class GeneratedSkill {
        private final String name;
        private final String triggerTask;
        private final String content;
        private final Instant createdAt;
        private int useCount;

        public GeneratedSkill(String name, String triggerTask, String content,
                              Instant createdAt, int useCount) {
            this.name = name;
            this.triggerTask = triggerTask;
            this.content = content;
            this.createdAt = createdAt;
            this.useCount = useCount;
        }

        public String getName() { return name; }
        public String getTriggerTask() { return triggerTask; }
        public String getContent() { return content; }
        public Instant getCreatedAt() { return createdAt; }
        public int getUseCount() { return useCount; }
        public void incrementUse() { useCount++; }
    }

    private static class TaskRecord {
        final String task;
        final String result;
        final String sessionId;
        final Instant timestamp;

        TaskRecord(String task, String result, String sessionId, Instant timestamp) {
            this.task = task;
            this.result = result;
            this.sessionId = sessionId;
            this.timestamp = timestamp;
        }
    }
}
