package com.hermes.agent.skills;

import com.hermes.agent.skills.model.Skill;
import com.hermes.agent.skills.model.Skill.Source;
import com.hermes.agent.skills.loader.SkillLoader;
import com.hermes.agent.skills.loader.SkillWriter;
import com.hermes.agent.skills.hub.SkillsHubService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * 技能系统 - 基于文件系统的技能管理
 * 
 * 重构要点：
 * 1. 使用 SKILL.md 文件格式
 * 2. 三层目录结构：hub/custom/auto-generated
 * 3. 保留 SkillGenerator 自动学习机制
 */
@Component
public class SkillSystem {
    
    private static final Logger log = LoggerFactory.getLogger(SkillSystem.class);
    
    private final SkillLoader skillLoader;
    private final SkillWriter skillWriter;
    private final SkillsHubService hubService;
    
    // 内存缓存
    private final Map<String, Skill> skills = new ConcurrentHashMap<>();
    private final Set<String> autoGeneratedSkillNames = ConcurrentHashMap.newKeySet();
    
    // 加载状态
    private volatile boolean loaded = false;
    
    public SkillSystem(SkillLoader skillLoader, SkillWriter skillWriter, SkillsHubService hubService) {
        this.skillLoader = skillLoader;
        this.skillWriter = skillWriter;
        this.hubService = hubService;
    }
    
    @PostConstruct
    public void init() {
        loadSkills();
    }
    
    /**
     * 从文件系统加载所有技能
     */
    public synchronized void loadSkills() {
        if (loaded) {
            log.warn("Skills already loaded, skipping");
            return;
        }
        
        log.info("Loading skills from filesystem...");
        
        try {
            Map<String, Skill> loadedSkills = skillLoader.loadAll();
            skills.putAll(loadedSkills);
            loaded = true;
            
            log.info("Loaded {} skills from filesystem", skills.size());
            
            // 统计各来源技能数量
            Map<Source, Long> bySource = skills.values().stream()
                .collect(Collectors.groupingBy(Skill::getSource, Collectors.counting()));
            bySource.forEach((source, count) -> 
                log.info("  - {}: {} skills", source.getDir(), count));
            
        } catch (Exception e) {
            log.error("Failed to load skills", e);
            registerDefaultSkills();
        }
    }
    
    /**
     * 重新加载技能（热重载）
     */
    public synchronized void reload() {
        log.info("Reloading all skills...");
        skills.clear();
        autoGeneratedSkillNames.clear();
        loaded = false;
        loadSkills();
    }
    
    /**
     * 注册默认技能（仅作为后备）
     */
    private void registerDefaultSkills() {
        log.info("Registering default skills as fallback");
        
        // 代码审查
        Skill codeReview = new Skill("code_review",
            "Reviews code for bugs, security issues, and best practices",
            """
            # Code Review Skill
            
            ## 适用场景
            - 代码合并前的审查
            - 发现潜在安全漏洞
            - 检查代码规范遵循
            
            ## 审查要点
            1. 代码逻辑正确性
            2. 边界条件处理
            3. 异常处理完整性
            4. 性能隐患
            5. 安全漏洞（SQL注入、XSS等）
            
            ## 注意事项
            - 关注实际风险，而非风格偏好
            - 提供具体修复建议，而非泛泛而谈
            """);
        codeReview.setSource(Source.CUSTOM);
        codeReview.setAuthor("Hermes Team");
        skills.put(codeReview.getName(), codeReview);
        
        // 调试
        Skill debug = new Skill("debug",
            "Helps debug code issues and provides solutions",
            """
            # Debug Skill
            
            ## 适用场景
            - 运行时错误分析
            - 性能问题定位
            - 异常堆栈解读
            
            ## 调试步骤
            1. 收集错误信息和堆栈
            2. 定位问题代码位置
            3. 分析可能原因
            4. 验证假设
            5. 提供修复方案
            
            ## 常见问题类型
            - 空指针异常
            - 类型转换错误
            - 并发问题
            - 资源泄漏
            """);
        debug.setSource(Source.CUSTOM);
        debug.setAuthor("Hermes Team");
        skills.put(debug.getName(), debug);
        
        // 重构
        Skill refactor = new Skill("refactor",
            "Refactors code to improve quality and readability",
            """
            # Refactor Skill
            
            ## 适用场景
            - 代码可读性提升
            - 减少重复代码
            - 简化复杂逻辑
            
            ## 重构原则
            1. 小步重构，每次只改一点
            2. 保持测试通过
            3. 提交前确保功能不变
            
            ## 常见重构模式
            - 提取方法
            - 提取变量
            - 移动方法
            - 内联变量
            """);
        refactor.setSource(Source.CUSTOM);
        refactor.setAuthor("Hermes Team");
        skills.put(refactor.getName(), refactor);
    }
    
    /**
     * 注册技能（内存 + 文件系统）
     */
    public void registerSkill(Skill skill) {
        Objects.requireNonNull(skill, "Skill cannot be null");
        Objects.requireNonNull(skill.getName(), "Skill name cannot be null");
        
        skills.put(skill.getName(), skill);
        
        // 如果有文件路径，尝试保存
        if (skill.getSource() != null) {
            try {
                skillWriter.save(skill);
                log.info("Saved skill to filesystem: {}", skill.getName());
            } catch (Exception e) {
                log.warn("Failed to save skill {}: {}", skill.getName(), e.getMessage());
            }
        }
        
        log.info("Registered skill: {} (source: {})", skill.getName(), skill.getSource());
    }
    
    /**
     * 获取技能
     */
    public Optional<Skill> getSkill(String name) {
        return Optional.ofNullable(skills.get(name));
    }
    
    /**
     * 搜索技能
     */
    public List<Skill> searchSkills(String query) {
        if (query == null || query.isBlank()) {
            return new ArrayList<>(skills.values());
        }
        
        String lowerQuery = query.toLowerCase();
        return skills.values().stream()
            .filter(s -> s.getName().toLowerCase().contains(lowerQuery) ||
                        s.getDescription().toLowerCase().contains(lowerQuery) ||
                        s.getTags().stream().anyMatch(t -> t.toLowerCase().contains(lowerQuery)))
            .sorted(Comparator.comparing(Skill::getName))
            .toList();
    }
    
    /**
     * 获取所有技能
     */
    public Map<String, Skill> getAllSkills() {
        return Collections.unmodifiableMap(skills);
    }
    
    /**
     * 获取所有技能名称
     */
    public List<String> getAllSkillNames() {
        return new ArrayList<>(skills.keySet());
    }
    
    /**
     * 删除技能
     */
    public boolean deleteSkill(String name) {
        Skill skill = skills.get(name);
        if (skill == null) {
            return false;
        }
        
        // 不允许删除 Hub 安装的技能（应通过 Hub 服务管理）
        if (skill.getSource() == Source.HUB) {
            log.warn("Cannot delete Hub-installed skill directly: {}", name);
            return false;
        }
        
        try {
            skillWriter.delete(skill);
            skills.remove(name);
            autoGeneratedSkillNames.remove(name);
            log.info("Deleted skill: {}", name);
            return true;
        } catch (Exception e) {
            log.error("Failed to delete skill {}: {}", name, e.getMessage());
            return false;
        }
    }
    
    /**
     * 标记为自动生成
     */
    public void markAutoGenerated(String name) {
        autoGeneratedSkillNames.add(name);
    }
    
    /**
     * 检查是否自动生成
     */
    public boolean isAutoGenerated(String name) {
        return autoGeneratedSkillNames.contains(name);
    }
    
    /**
     * 获取自动生成的技能名称集合
     */
    public Set<String> getAutoGeneratedSkillNames() {
        return Collections.unmodifiableSet(autoGeneratedSkillNames);
    }
    
    /**
     * 构建技能的提示内容（用于注入到系统提示）
     */
    public String buildSkillsPrompt(Set<String> skillNames) {
        if (skillNames == null || skillNames.isEmpty()) {
            return "";
        }
        
        StringBuilder sb = new StringBuilder();
        sb.append("\n## Loaded Skills\n\n");
        
        for (String name : skillNames) {
            Skill skill = skills.get(name);
            if (skill != null) {
                sb.append("### ").append(name).append("\n");
                sb.append(skill.getContent()).append("\n\n");
            }
        }
        
        return sb.toString();
    }
    
    /**
     * 获取统计信息
     */
    public Map<String, Object> getSkillStats() {
        Map<String, Object> stats = new LinkedHashMap<>();
        stats.put("total_skills", skills.size());
        stats.put("auto_generated", autoGeneratedSkillNames.size());
        
        // 按来源统计
        Map<String, Long> bySource = skills.values().stream()
            .collect(Collectors.groupingBy(
                s -> s.getSource() != null ? s.getSource().getDir() : "unknown",
                Collectors.counting()
            ));
        stats.put("by_source", bySource);
        
        stats.put("skill_names", getAllSkillNames());
        return stats;
    }
    
    // === 兼容旧 API 的方法 ===
    
    /**
     * @deprecated 使用 getSkill(String).map(Skill::getDescription) 代替
     */
    @Deprecated
    public void improveSkill(String name, String improvement) {
        getSkill(name).ifPresent(skill -> {
            String newContent = skill.getContent() + "\n\n## Improvement: " + improvement;
            skill.setContent(newContent);
            try {
                skillWriter.save(skill);
                log.info("Improved skill: {}", name);
            } catch (Exception e) {
                log.error("Failed to save improved skill: {}", name, e);
            }
        });
    }
}
